# Redes Neurais Artificiais com Keras

In [10]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import np_utils

import numpy as np

In [7]:
base = datasets.load_iris()
previsores = base.data
classe = base.target
classe

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [8]:
# Criação de classe_dummy para a rede neural com três neironios na camada de saída
class_dummy = np_utils.to_categorical(classe)
class_dummy

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [9]:
X_train, X_test, y_train, y_test = train_test_split(previsores, class_dummy, test_size=0.3, random_state=0)

Criamos agora a estrutura da RNA com a class Sequential (Sequência de camadas)

In [11]:
model = Sequential()

# Primeira camada oculta, 5neuronios. 4 Neuronios de entrada.
model.add(Dense(units=5, input_dim=4))
# Segunda camada Oculta
model.add(Dense(units=4))

# Terceira camada oculta.
# Adicionaos a função de ativação 'softmax' por conta de um problema de classificação com mais de duas classes
# (É gerada uma prob em cada neurônio)
model.add(Dense(units=3, activation='softmax'))

In [12]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 5)                 25        
_________________________________________________________________
dense_4 (Dense)              (None, 4)                 24        
_________________________________________________________________
dense_5 (Dense)              (None, 3)                 15        
Total params: 64
Trainable params: 64
Non-trainable params: 0
_________________________________________________________________


In [14]:
# Adam -> Algoritmo para atualizar os pesos. Loss = cálculo do erro. 
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

model.fit(X_train, y_train, epochs = 1000, validation_data=(X_test, y_test))

Epoch 1/1000
4/4 [==============================] - 1s 67ms/step - loss: 1.3850 - accuracy: 0.3798 - val_loss: 1.6569 - val_accuracy: 0.2444
Epoch 2/1000
4/4 [==============================] - 0s 12ms/step - loss: 1.2734 - accuracy: 0.4038 - val_loss: 1.5424 - val_accuracy: 0.2444
Epoch 3/1000
4/4 [==============================] - 0s 13ms/step - loss: 1.2688 - accuracy: 0.3611 - val_loss: 1.4393 - val_accuracy: 0.2444
Epoch 4/1000
4/4 [==============================] - 0s 14ms/step - loss: 1.1977 - accuracy: 0.3746 - val_loss: 1.3503 - val_accuracy: 0.2444
Epoch 5/1000
4/4 [==============================] - 0s 15ms/step - loss: 1.1742 - accuracy: 0.3496 - val_loss: 1.2752 - val_accuracy: 0.2444
Epoch 6/1000
4/4 [==============================] - 0s 15ms/step - loss: 1.1017 - accuracy: 0.3642 - val_loss: 1.2140 - val_accuracy: 0.2444
Epoch 7/1000
4/4 [==============================] - 0s 15ms/step - loss: 1.0666 - accuracy: 0.3673 - val_loss: 1.1657 - val_accuracy: 0.2444
Epoch 8/1000


Epoch 59/1000
4/4 [==============================] - 0s 14ms/step - loss: 0.5811 - accuracy: 0.6625 - val_loss: 0.6007 - val_accuracy: 0.6000
Epoch 60/1000
4/4 [==============================] - 0s 13ms/step - loss: 0.5584 - accuracy: 0.7038 - val_loss: 0.5920 - val_accuracy: 0.6000
Epoch 61/1000
4/4 [==============================] - 0s 13ms/step - loss: 0.5384 - accuracy: 0.7236 - val_loss: 0.5820 - val_accuracy: 0.6000
Epoch 62/1000
4/4 [==============================] - 0s 12ms/step - loss: 0.5398 - accuracy: 0.7267 - val_loss: 0.5731 - val_accuracy: 0.6222
Epoch 63/1000
4/4 [==============================] - 0s 12ms/step - loss: 0.5344 - accuracy: 0.7090 - val_loss: 0.5681 - val_accuracy: 0.6222
Epoch 64/1000
4/4 [==============================] - 0s 13ms/step - loss: 0.5216 - accuracy: 0.7381 - val_loss: 0.5659 - val_accuracy: 0.6222
Epoch 65/1000
4/4 [==============================] - 0s 11ms/step - loss: 0.5190 - accuracy: 0.7284 - val_loss: 0.5672 - val_accuracy: 0.6000
Epoch 

4/4 [==============================] - 0s 12ms/step - loss: 0.1925 - accuracy: 0.9757 - val_loss: 0.2349 - val_accuracy: 0.9556
Epoch 174/1000
4/4 [==============================] - 0s 12ms/step - loss: 0.1849 - accuracy: 0.9788 - val_loss: 0.2326 - val_accuracy: 0.9556
Epoch 175/1000
4/4 [==============================] - 0s 12ms/step - loss: 0.1926 - accuracy: 0.9757 - val_loss: 0.2339 - val_accuracy: 0.9556
Epoch 176/1000
4/4 [==============================] - 0s 12ms/step - loss: 0.1810 - accuracy: 0.9851 - val_loss: 0.2288 - val_accuracy: 0.9556
Epoch 177/1000
4/4 [==============================] - 0s 11ms/step - loss: 0.1899 - accuracy: 0.9757 - val_loss: 0.2276 - val_accuracy: 0.9556
Epoch 178/1000
4/4 [==============================] - 0s 12ms/step - loss: 0.1861 - accuracy: 0.9757 - val_loss: 0.2388 - val_accuracy: 0.9556
Epoch 179/1000
4/4 [==============================] - 0s 13ms/step - loss: 0.1690 - accuracy: 0.9775 - val_loss: 0.2456 - val_accuracy: 0.9333
Epoch 180/1000

4/4 [==============================] - 0s 13ms/step - loss: 0.0977 - accuracy: 0.9757 - val_loss: 0.1358 - val_accuracy: 0.9778
Epoch 288/1000
4/4 [==============================] - 0s 16ms/step - loss: 0.0853 - accuracy: 0.9788 - val_loss: 0.1379 - val_accuracy: 0.9778
Epoch 289/1000
4/4 [==============================] - 0s 13ms/step - loss: 0.0856 - accuracy: 0.9788 - val_loss: 0.1439 - val_accuracy: 0.9778
Epoch 290/1000
4/4 [==============================] - 0s 13ms/step - loss: 0.0959 - accuracy: 0.9695 - val_loss: 0.1525 - val_accuracy: 0.9556
Epoch 291/1000
4/4 [==============================] - 0s 13ms/step - loss: 0.0807 - accuracy: 0.9820 - val_loss: 0.1535 - val_accuracy: 0.9556
Epoch 292/1000
4/4 [==============================] - 0s 14ms/step - loss: 0.0910 - accuracy: 0.9788 - val_loss: 0.1525 - val_accuracy: 0.9556
Epoch 293/1000
4/4 [==============================] - 0s 13ms/step - loss: 0.0789 - accuracy: 0.9851 - val_loss: 0.1443 - val_accuracy: 0.9778
Epoch 294/1000

4/4 [==============================] - 0s 15ms/step - loss: 0.0601 - accuracy: 0.9757 - val_loss: 0.1158 - val_accuracy: 0.9778
Epoch 402/1000
4/4 [==============================] - 0s 14ms/step - loss: 0.0650 - accuracy: 0.9695 - val_loss: 0.1149 - val_accuracy: 0.9778
Epoch 403/1000
4/4 [==============================] - 0s 16ms/step - loss: 0.0591 - accuracy: 0.9788 - val_loss: 0.1197 - val_accuracy: 0.9778
Epoch 404/1000
4/4 [==============================] - 0s 13ms/step - loss: 0.0515 - accuracy: 0.9872 - val_loss: 0.1250 - val_accuracy: 0.9778
Epoch 405/1000
4/4 [==============================] - 0s 14ms/step - loss: 0.0654 - accuracy: 0.9757 - val_loss: 0.1227 - val_accuracy: 0.9778
Epoch 406/1000
4/4 [==============================] - 0s 13ms/step - loss: 0.0569 - accuracy: 0.9851 - val_loss: 0.1238 - val_accuracy: 0.9778
Epoch 407/1000
4/4 [==============================] - 0s 12ms/step - loss: 0.0604 - accuracy: 0.9788 - val_loss: 0.1216 - val_accuracy: 0.9778
Epoch 408/1000

4/4 [==============================] - 0s 11ms/step - loss: 0.0483 - accuracy: 0.9788 - val_loss: 0.1133 - val_accuracy: 0.9778
Epoch 516/1000
4/4 [==============================] - 0s 11ms/step - loss: 0.0434 - accuracy: 0.9851 - val_loss: 0.1137 - val_accuracy: 0.9778
Epoch 517/1000
4/4 [==============================] - 0s 11ms/step - loss: 0.0418 - accuracy: 0.9882 - val_loss: 0.1136 - val_accuracy: 0.9778
Epoch 518/1000
4/4 [==============================] - 0s 11ms/step - loss: 0.0439 - accuracy: 0.9851 - val_loss: 0.1099 - val_accuracy: 0.9778
Epoch 519/1000
4/4 [==============================] - 0s 11ms/step - loss: 0.0479 - accuracy: 0.9788 - val_loss: 0.1079 - val_accuracy: 0.9778
Epoch 520/1000
4/4 [==============================] - 0s 11ms/step - loss: 0.0410 - accuracy: 0.9882 - val_loss: 0.1076 - val_accuracy: 0.9778
Epoch 521/1000
4/4 [==============================] - 0s 11ms/step - loss: 0.0448 - accuracy: 0.9788 - val_loss: 0.1076 - val_accuracy: 0.9778
Epoch 522/1000

4/4 [==============================] - 0s 12ms/step - loss: 0.0504 - accuracy: 0.9757 - val_loss: 0.1075 - val_accuracy: 0.9778
Epoch 630/1000
4/4 [==============================] - 0s 13ms/step - loss: 0.0498 - accuracy: 0.9695 - val_loss: 0.1066 - val_accuracy: 0.9778
Epoch 631/1000
4/4 [==============================] - 0s 13ms/step - loss: 0.0315 - accuracy: 0.9882 - val_loss: 0.1111 - val_accuracy: 0.9778
Epoch 632/1000
4/4 [==============================] - 0s 12ms/step - loss: 0.0417 - accuracy: 0.9757 - val_loss: 0.1140 - val_accuracy: 0.9778
Epoch 633/1000
4/4 [==============================] - 0s 12ms/step - loss: 0.0368 - accuracy: 0.9820 - val_loss: 0.1199 - val_accuracy: 0.9778
Epoch 634/1000
4/4 [==============================] - 0s 12ms/step - loss: 0.0456 - accuracy: 0.9882 - val_loss: 0.1242 - val_accuracy: 0.9778
Epoch 635/1000
4/4 [==============================] - 0s 12ms/step - loss: 0.0458 - accuracy: 0.9809 - val_loss: 0.1162 - val_accuracy: 0.9778
Epoch 636/1000

4/4 [==============================] - 0s 13ms/step - loss: 0.0404 - accuracy: 0.9820 - val_loss: 0.1113 - val_accuracy: 0.9778
Epoch 744/1000
4/4 [==============================] - 0s 11ms/step - loss: 0.0359 - accuracy: 0.9820 - val_loss: 0.1080 - val_accuracy: 0.9778
Epoch 745/1000
4/4 [==============================] - 0s 12ms/step - loss: 0.0434 - accuracy: 0.9788 - val_loss: 0.1082 - val_accuracy: 0.9778
Epoch 746/1000
4/4 [==============================] - 0s 12ms/step - loss: 0.0405 - accuracy: 0.9788 - val_loss: 0.1080 - val_accuracy: 0.9778
Epoch 747/1000
4/4 [==============================] - 0s 12ms/step - loss: 0.0404 - accuracy: 0.9851 - val_loss: 0.1109 - val_accuracy: 0.9778
Epoch 748/1000
4/4 [==============================] - 0s 11ms/step - loss: 0.0436 - accuracy: 0.9809 - val_loss: 0.1110 - val_accuracy: 0.9778
Epoch 749/1000
4/4 [==============================] - 0s 12ms/step - loss: 0.0477 - accuracy: 0.9695 - val_loss: 0.1051 - val_accuracy: 0.9778
Epoch 750/1000

4/4 [==============================] - 0s 10ms/step - loss: 0.0432 - accuracy: 0.9847 - val_loss: 0.1059 - val_accuracy: 0.9778
Epoch 858/1000
4/4 [==============================] - 0s 11ms/step - loss: 0.0332 - accuracy: 0.9941 - val_loss: 0.1085 - val_accuracy: 0.9778
Epoch 859/1000
4/4 [==============================] - 0s 10ms/step - loss: 0.0394 - accuracy: 0.9941 - val_loss: 0.1119 - val_accuracy: 0.9778
Epoch 860/1000
4/4 [==============================] - 0s 10ms/step - loss: 0.0388 - accuracy: 0.9820 - val_loss: 0.1139 - val_accuracy: 0.9778
Epoch 861/1000
4/4 [==============================] - 0s 10ms/step - loss: 0.0479 - accuracy: 0.9695 - val_loss: 0.1107 - val_accuracy: 0.9778
Epoch 862/1000
4/4 [==============================] - 0s 10ms/step - loss: 0.0432 - accuracy: 0.9788 - val_loss: 0.1100 - val_accuracy: 0.9778
Epoch 863/1000
4/4 [==============================] - 0s 11ms/step - loss: 0.0339 - accuracy: 0.9788 - val_loss: 0.1102 - val_accuracy: 0.9778
Epoch 864/1000

4/4 [==============================] - 0s 12ms/step - loss: 0.0360 - accuracy: 0.9788 - val_loss: 0.1178 - val_accuracy: 0.9778
Epoch 972/1000
4/4 [==============================] - 0s 12ms/step - loss: 0.0326 - accuracy: 0.9851 - val_loss: 0.1183 - val_accuracy: 0.9778
Epoch 973/1000
4/4 [==============================] - 0s 11ms/step - loss: 0.0341 - accuracy: 0.9851 - val_loss: 0.1158 - val_accuracy: 0.9778
Epoch 974/1000
4/4 [==============================] - 0s 12ms/step - loss: 0.0304 - accuracy: 0.9809 - val_loss: 0.1111 - val_accuracy: 0.9778
Epoch 975/1000
4/4 [==============================] - 0s 12ms/step - loss: 0.0366 - accuracy: 0.9847 - val_loss: 0.1053 - val_accuracy: 0.9778
Epoch 976/1000
4/4 [==============================] - 0s 12ms/step - loss: 0.0332 - accuracy: 0.9962 - val_loss: 0.1056 - val_accuracy: 0.9778
Epoch 977/1000
4/4 [==============================] - 0s 12ms/step - loss: 0.0383 - accuracy: 1.0000 - val_loss: 0.1111 - val_accuracy: 0.9778
Epoch 978/1000

In [18]:
prev = model.predict(X_test)
prev = prev > 0.5
prev

array([[False, False,  True],
       [False,  True, False],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [False, False,  True],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [ True, False, False],
       [False,  True, False],
       [False,  True, False],
       [ True, False, False],
       [ True, False, False],
       [False, False,  True],
       [False,  True, False],
       [ True, False, False],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [ True, False, False],
       [False,  True, False],
       [False,  True, False],
       [ True, False, False],
       [False, False,  True],
       [False,  True, False],
       [ True, False, False],
       [Fa

In [19]:
#Como são três saidas, precisamos encontrar a posição de maior valor probabilistico
y_test_matrix= [np.argmax(t) for t in y_test]
y_prev_matrix = [np.argmax(t) for t in prev]

In [22]:
conf = confusion_matrix(y_test_matrix, y_prev_matrix)
conf

array([[16,  0,  0],
       [ 0, 17,  1],
       [ 0,  0, 11]])