# Qui-Quadrado
Analisa se as diferenças significantes além das diferenças do acaso;

In [2]:
import numpy as np
from scipy.stats import chi2_contingency

In [3]:
novela = np.array([[19, 6],[43, 32]])
novela

array([[19,  6],
       [43, 32]])

Vimos então que p é maior que 0.05, logo a hipotese nula não foi anulada!

In [4]:
novela2 = np.array([[22, 3], [43, 32]])
novela2

array([[22,  3],
       [43, 32]])

In [5]:
chi2_contingency(novela2) 

(6.461538461538461,
 0.011023416388221425,
 1,
 array([[16.25,  8.75],
        [48.75, 26.25]]))

Vimos aqui que o pvalue é menor que 0.05, logo a hipotese nula não é válida, então **temos** diferenças significativas 